DROP TABLE IF EXISTS ROLLERS;
CREATE TABLE ROLLERS(
       ID INT PRIMARY	KEY		NOT NULL,
       TYPE   		TEXT	    	NOT NULL,
       MANUFACTURER	CHAR(25)	NOT NULL,
       PART_NUMBER	CHAR(25),
       BEARINGS		CHAR(25),
       RETAIN		CHAR(25),
       UPTIME		REAL
);
       
