DROP TABLE IF EXISTS RIGS;
CREATE TABLE RIGS(
       ID INT PRIMARY	KEY		NOT NULL,
       HOSTNAME		TEXT	    	NOT NULL,
       STATION_NUM	INT		NOT NULL,
       IP_ADDRESS	CHAR(15)       	NOT NULL
);
       
