DROP TABLE IF EXISTS STATIONS;
CREATE TABLE STATIONS(
       ID INTEGER PRIMARY KEY	AUTOINCREMENT,
       STATION_ID	INT	NOT NULL,
       RIG_ID 		INT	NOT NULL,
       ROLLER_ID	INT,
       LAST_INSTALL	REAL
);
       
