DROP TABLE IF EXISTS HISTORY;
CREATE TABLE HISTORY(
       ID INTEGER	PRIMARY KEY	AUTOINCREMENT,
       TIME_STAMP 	REAL	  	NOT NULL,
       RIG_ID	  	INT	  	NOT NULL,
       STATION_ID	INT		NOT NULL,
       ROLLER_ID  	INT		NOT NULL,
       DATE_STRING 	CHAR(25)	NOT NULL,	--Expected format %Y-%m-%dT%H:%M:%S%ZZZZ
       COMMENT	   	TEXT
);
